// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kprobe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KernelEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TimestampNs   uint64                 `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Pid           uint32                 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	TraceId       string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelEventProto) Reset() {
	*x = KernelEventProto{}
	mi := &file_kprobe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelEventProto) ProtoMessage() {}

func (x *KernelEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelEventProto.ProtoReflect.Descriptor instead.
func (*KernelEventProto) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{0}
}

func (x *KernelEventProto) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *KernelEventProto) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *KernelEventProto) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *KernelEventProto) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *KernelEventProto) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *KernelEventProto) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *KernelEventProto) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CausalEdgeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromEventId   string                 `protobuf:"bytes,1,opt,name=from_event_id,json=fromEventId,proto3" json:"from_event_id,omitempty"`
	ToEventId     string                 `protobuf:"bytes,2,opt,name=to_event_id,json=toEventId,proto3" json:"to_event_id,omitempty"`
	CauseType     string                 `protobuf:"bytes,3,opt,name=cause_type,json=causeType,proto3" json:"cause_type,omitempty"`
	LatencyNs     uint64                 `protobuf:"varint,4,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CausalEdgeProto) Reset() {
	*x = CausalEdgeProto{}
	mi := &file_kprobe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CausalEdgeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CausalEdgeProto) ProtoMessage() {}

func (x *CausalEdgeProto) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CausalEdgeProto.ProtoReflect.Descriptor instead.
func (*CausalEdgeProto) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{1}
}

func (x *CausalEdgeProto) GetFromEventId() string {
	if x != nil {
		return x.FromEventId
	}
	return ""
}

func (x *CausalEdgeProto) GetToEventId() string {
	if x != nil {
		return x.ToEventId
	}
	return ""
}

func (x *CausalEdgeProto) GetCauseType() string {
	if x != nil {
		return x.CauseType
	}
	return ""
}

func (x *CausalEdgeProto) GetLatencyNs() uint64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

func (x *CausalEdgeProto) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CausalEdgeProto) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type QueryCausalChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCausalChainRequest) Reset() {
	*x = QueryCausalChainRequest{}
	mi := &file_kprobe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCausalChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCausalChainRequest) ProtoMessage() {}

func (x *QueryCausalChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCausalChainRequest.ProtoReflect.Descriptor instead.
func (*QueryCausalChainRequest) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{2}
}

func (x *QueryCausalChainRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type QueryCausalChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*KernelEventProto    `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*CausalEdgeProto     `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCausalChainResponse) Reset() {
	*x = QueryCausalChainResponse{}
	mi := &file_kprobe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCausalChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCausalChainResponse) ProtoMessage() {}

func (x *QueryCausalChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCausalChainResponse.ProtoReflect.Descriptor instead.
func (*QueryCausalChainResponse) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{3}
}

func (x *QueryCausalChainResponse) GetNodes() []*KernelEventProto {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *QueryCausalChainResponse) GetEdges() []*CausalEdgeProto {
	if x != nil {
		return x.Edges
	}
	return nil
}

type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_kprobe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{4}
}

func (x *QueryEventsRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*KernelEventProto    `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_kprobe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{5}
}

func (x *QueryEventsResponse) GetEvents() []*KernelEventProto {
	if x != nil {
		return x.Events
	}
	return nil
}

type QueryTimeRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNs        uint64                 `protobuf:"varint,1,opt,name=from_ns,json=fromNs,proto3" json:"from_ns,omitempty"`
	ToNs          uint64                 `protobuf:"varint,2,opt,name=to_ns,json=toNs,proto3" json:"to_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTimeRangeRequest) Reset() {
	*x = QueryTimeRangeRequest{}
	mi := &file_kprobe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTimeRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTimeRangeRequest) ProtoMessage() {}

func (x *QueryTimeRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTimeRangeRequest.ProtoReflect.Descriptor instead.
func (*QueryTimeRangeRequest) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{6}
}

func (x *QueryTimeRangeRequest) GetFromNs() uint64 {
	if x != nil {
		return x.FromNs
	}
	return 0
}

func (x *QueryTimeRangeRequest) GetToNs() uint64 {
	if x != nil {
		return x.ToNs
	}
	return 0
}

type QueryTimeRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*KernelEventProto    `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTimeRangeResponse) Reset() {
	*x = QueryTimeRangeResponse{}
	mi := &file_kprobe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTimeRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTimeRangeResponse) ProtoMessage() {}

func (x *QueryTimeRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTimeRangeResponse.ProtoReflect.Descriptor instead.
func (*QueryTimeRangeResponse) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{7}
}

func (x *QueryTimeRangeResponse) GetEvents() []*KernelEventProto {
	if x != nil {
		return x.Events
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_kprobe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{8}
}

type StreamEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *KernelEventProto      `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_kprobe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{9}
}

func (x *StreamEventsResponse) GetEvent() *KernelEventProto {
	if x != nil {
		return x.Event
	}
	return nil
}

type StartReplayRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionId     string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TimeoutOverrideNs uint64                 `protobuf:"varint,2,opt,name=timeout_override_ns,json=timeoutOverrideNs,proto3" json:"timeout_override_ns,omitempty"`
	LatencyMultiplier float64                `protobuf:"fixed64,3,opt,name=latency_multiplier,json=latencyMultiplier,proto3" json:"latency_multiplier,omitempty"`
	ExtraLatencyNs    uint64                 `protobuf:"varint,4,opt,name=extra_latency_ns,json=extraLatencyNs,proto3" json:"extra_latency_ns,omitempty"`
	InjectFailureAt   string                 `protobuf:"bytes,5,opt,name=inject_failure_at,json=injectFailureAt,proto3" json:"inject_failure_at,omitempty"`
	SpeedFactor       float64                `protobuf:"fixed64,6,opt,name=speed_factor,json=speedFactor,proto3" json:"speed_factor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartReplayRequest) Reset() {
	*x = StartReplayRequest{}
	mi := &file_kprobe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReplayRequest) ProtoMessage() {}

func (x *StartReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReplayRequest.ProtoReflect.Descriptor instead.
func (*StartReplayRequest) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{10}
}

func (x *StartReplayRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *StartReplayRequest) GetTimeoutOverrideNs() uint64 {
	if x != nil {
		return x.TimeoutOverrideNs
	}
	return 0
}

func (x *StartReplayRequest) GetLatencyMultiplier() float64 {
	if x != nil {
		return x.LatencyMultiplier
	}
	return 0
}

func (x *StartReplayRequest) GetExtraLatencyNs() uint64 {
	if x != nil {
		return x.ExtraLatencyNs
	}
	return 0
}

func (x *StartReplayRequest) GetInjectFailureAt() string {
	if x != nil {
		return x.InjectFailureAt
	}
	return ""
}

func (x *StartReplayRequest) GetSpeedFactor() float64 {
	if x != nil {
		return x.SpeedFactor
	}
	return 0
}

type StartReplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventCount    int32                  `protobuf:"varint,2,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	Injections    string                 `protobuf:"bytes,3,opt,name=injections,proto3" json:"injections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReplayResponse) Reset() {
	*x = StartReplayResponse{}
	mi := &file_kprobe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReplayResponse) ProtoMessage() {}

func (x *StartReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReplayResponse.ProtoReflect.Descriptor instead.
func (*StartReplayResponse) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{11}
}

func (x *StartReplayResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartReplayResponse) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *StartReplayResponse) GetInjections() string {
	if x != nil {
		return x.Injections
	}
	return ""
}

type ReplayControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	SeekIndex     int32                  `protobuf:"varint,3,opt,name=seek_index,json=seekIndex,proto3" json:"seek_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayControlRequest) Reset() {
	*x = ReplayControlRequest{}
	mi := &file_kprobe_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayControlRequest) ProtoMessage() {}

func (x *ReplayControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayControlRequest.ProtoReflect.Descriptor instead.
func (*ReplayControlRequest) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{12}
}

func (x *ReplayControlRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayControlRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ReplayControlRequest) GetSeekIndex() int32 {
	if x != nil {
		return x.SeekIndex
	}
	return 0
}

type ReplayControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Cursor        int32                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayControlResponse) Reset() {
	*x = ReplayControlResponse{}
	mi := &file_kprobe_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayControlResponse) ProtoMessage() {}

func (x *ReplayControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayControlResponse.ProtoReflect.Descriptor instead.
func (*ReplayControlResponse) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{13}
}

func (x *ReplayControlResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayControlResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ReplayControlResponse) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type ReplayStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayStatusRequest) Reset() {
	*x = ReplayStatusRequest{}
	mi := &file_kprobe_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayStatusRequest) ProtoMessage() {}

func (x *ReplayStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayStatusRequest.ProtoReflect.Descriptor instead.
func (*ReplayStatusRequest) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{14}
}

func (x *ReplayStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ReplayStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Cursor        int32                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	EventCount    int32                  `protobuf:"varint,4,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	Injections    string                 `protobuf:"bytes,5,opt,name=injections,proto3" json:"injections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayStatusResponse) Reset() {
	*x = ReplayStatusResponse{}
	mi := &file_kprobe_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayStatusResponse) ProtoMessage() {}

func (x *ReplayStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayStatusResponse.ProtoReflect.Descriptor instead.
func (*ReplayStatusResponse) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{15}
}

func (x *ReplayStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ReplayStatusResponse) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ReplayStatusResponse) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *ReplayStatusResponse) GetInjections() string {
	if x != nil {
		return x.Injections
	}
	return ""
}

type ReplayEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TimestampNs   uint64                 `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Pid           uint32                 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	DurationNs    uint64                 `protobuf:"varint,7,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	ReturnValue   int64                  `protobuf:"varint,8,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	Index         int32                  `protobuf:"varint,9,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayEventProto) Reset() {
	*x = ReplayEventProto{}
	mi := &file_kprobe_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayEventProto) ProtoMessage() {}

func (x *ReplayEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayEventProto.ProtoReflect.Descriptor instead.
func (*ReplayEventProto) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{16}
}

func (x *ReplayEventProto) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReplayEventProto) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ReplayEventProto) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ReplayEventProto) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ReplayEventProto) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ReplayEventProto) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ReplayEventProto) GetDurationNs() uint64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *ReplayEventProto) GetReturnValue() int64 {
	if x != nil {
		return x.ReturnValue
	}
	return 0
}

func (x *ReplayEventProto) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type WatchReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchReplayRequest) Reset() {
	*x = WatchReplayRequest{}
	mi := &file_kprobe_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchReplayRequest) ProtoMessage() {}

func (x *WatchReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchReplayRequest.ProtoReflect.Descriptor instead.
func (*WatchReplayRequest) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{17}
}

func (x *WatchReplayRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WatchReplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ReplayEventProto      `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchReplayResponse) Reset() {
	*x = WatchReplayResponse{}
	mi := &file_kprobe_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchReplayResponse) ProtoMessage() {}

func (x *WatchReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kprobe_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchReplayResponse.ProtoReflect.Descriptor instead.
func (*WatchReplayResponse) Descriptor() ([]byte, []int) {
	return file_kprobe_proto_rawDescGZIP(), []int{18}
}

func (x *WatchReplayResponse) GetEvent() *ReplayEventProto {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchReplayResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_kprobe_proto protoreflect.FileDescriptor

const file_kprobe_proto_rawDesc = "" +
	"\n" +
	"\fkprobe.proto\x12\x06kprobe\"\xe6\x01\n" +
	"\x10KernelEventProto\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x04R\vtimestampNs\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\rR\x03pid\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\"\xdd\x01\n" +
	"\x0fCausalEdgeProto\x12\"\n" +
	"\rfrom_event_id\x18\x01 \x01(\tR\vfromEventId\x12\x1e\n" +
	"\vto_event_id\x18\x02 \x01(\tR\ttoEventId\x12\x1d\n" +
	"\n" +
	"cause_type\x18\x03 \x01(\tR\tcauseType\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\x04 \x01(\x04R\tlatencyNs\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\"@\n" +
	"\x17QueryCausalChainRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"y\n" +
	"\x18QueryCausalChainResponse\x12.\n" +
	"\x05nodes\x18\x01 \x03(\v2\x18.kprobe.KernelEventProtoR\x05nodes\x12-\n" +
	"\x05edges\x18\x02 \x03(\v2\x17.kprobe.CausalEdgeProtoR\x05edges\";\n" +
	"\x12QueryEventsRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"G\n" +
	"\x13QueryEventsResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.kprobe.KernelEventProtoR\x06events\"E\n" +
	"\x15QueryTimeRangeRequest\x12\x17\n" +
	"\afrom_ns\x18\x01 \x01(\x04R\x06fromNs\x12\x13\n" +
	"\x05to_ns\x18\x02 \x01(\x04R\x04toNs\"J\n" +
	"\x16QueryTimeRangeResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.kprobe.KernelEventProtoR\x06events\"\x15\n" +
	"\x13StreamEventsRequest\"F\n" +
	"\x14StreamEventsResponse\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x18.kprobe.KernelEventProtoR\x05event\"\x93\x02\n" +
	"\x12StartReplayRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12.\n" +
	"\x13timeout_override_ns\x18\x02 \x01(\x04R\x11timeoutOverrideNs\x12-\n" +
	"\x12latency_multiplier\x18\x03 \x01(\x01R\x11latencyMultiplier\x12(\n" +
	"\x10extra_latency_ns\x18\x04 \x01(\x04R\x0eextraLatencyNs\x12*\n" +
	"\x11inject_failure_at\x18\x05 \x01(\tR\x0finjectFailureAt\x12!\n" +
	"\fspeed_factor\x18\x06 \x01(\x01R\vspeedFactor\"u\n" +
	"\x13StartReplayResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vevent_count\x18\x02 \x01(\x05R\n" +
	"eventCount\x12\x1e\n" +
	"\n" +
	"injections\x18\x03 \x01(\tR\n" +
	"injections\"n\n" +
	"\x14ReplayControlRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1d\n" +
	"\n" +
	"seek_index\x18\x03 \x01(\x05R\tseekIndex\"d\n" +
	"\x15ReplayControlResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x05R\x06cursor\"4\n" +
	"\x13ReplayStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xa4\x01\n" +
	"\x14ReplayStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x05R\x06cursor\x12\x1f\n" +
	"\vevent_count\x18\x04 \x01(\x05R\n" +
	"eventCount\x12\x1e\n" +
	"\n" +
	"injections\x18\x05 \x01(\tR\n" +
	"injections\"\xa5\x02\n" +
	"\x10ReplayEventProto\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x04R\vtimestampNs\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\rR\x03pid\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vduration_ns\x18\a \x01(\x04R\n" +
	"durationNs\x12!\n" +
	"\freturn_value\x18\b \x01(\x03R\vreturnValue\x12\x14\n" +
	"\x05index\x18\t \x01(\x05R\x05index\"3\n" +
	"\x12WatchReplayRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"[\n" +
	"\x13WatchReplayResponse\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x18.kprobe.ReplayEventProtoR\x05event\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state2\xcc\x02\n" +
	"\rKprobeService\x12U\n" +
	"\x10QueryCausalChain\x12\x1f.kprobe.QueryCausalChainRequest\x1a .kprobe.QueryCausalChainResponse\x12F\n" +
	"\vQueryEvents\x12\x1a.kprobe.QueryEventsRequest\x1a\x1b.kprobe.QueryEventsResponse\x12O\n" +
	"\x0eQueryTimeRange\x12\x1d.kprobe.QueryTimeRangeRequest\x1a\x1e.kprobe.QueryTimeRangeResponse\x12K\n" +
	"\fStreamEvents\x12\x1b.kprobe.StreamEventsRequest\x1a\x1c.kprobe.StreamEventsResponse0\x012\xae\x02\n" +
	"\rReplayService\x12F\n" +
	"\vStartReplay\x12\x1a.kprobe.StartReplayRequest\x1a\x1b.kprobe.StartReplayResponse\x12F\n" +
	"\aControl\x12\x1c.kprobe.ReplayControlRequest\x1a\x1d.kprobe.ReplayControlResponse\x12C\n" +
	"\x06Status\x12\x1b.kprobe.ReplayStatusRequest\x1a\x1c.kprobe.ReplayStatusResponse\x12H\n" +
	"\vWatchReplay\x12\x1a.kprobe.WatchReplayRequest\x1a\x1b.kprobe.WatchReplayResponse0\x01B#Z!github.com/YHQZ1/kprobe/api/protob\x06proto3"

var (
	file_kprobe_proto_rawDescOnce sync.Once
	file_kprobe_proto_rawDescData []byte
)

func file_kprobe_proto_rawDescGZIP() []byte {
	file_kprobe_proto_rawDescOnce.Do(func() {
		file_kprobe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kprobe_proto_rawDesc), len(file_kprobe_proto_rawDesc)))
	})
	return file_kprobe_proto_rawDescData
}

var file_kprobe_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_kprobe_proto_goTypes = []any{
	(*KernelEventProto)(nil),         // 0: kprobe.KernelEventProto
	(*CausalEdgeProto)(nil),          // 1: kprobe.CausalEdgeProto
	(*QueryCausalChainRequest)(nil),  // 2: kprobe.QueryCausalChainRequest
	(*QueryCausalChainResponse)(nil), // 3: kprobe.QueryCausalChainResponse
	(*QueryEventsRequest)(nil),       // 4: kprobe.QueryEventsRequest
	(*QueryEventsResponse)(nil),      // 5: kprobe.QueryEventsResponse
	(*QueryTimeRangeRequest)(nil),    // 6: kprobe.QueryTimeRangeRequest
	(*QueryTimeRangeResponse)(nil),   // 7: kprobe.QueryTimeRangeResponse
	(*StreamEventsRequest)(nil),      // 8: kprobe.StreamEventsRequest
	(*StreamEventsResponse)(nil),     // 9: kprobe.StreamEventsResponse
	(*StartReplayRequest)(nil),       // 10: kprobe.StartReplayRequest
	(*StartReplayResponse)(nil),      // 11: kprobe.StartReplayResponse
	(*ReplayControlRequest)(nil),     // 12: kprobe.ReplayControlRequest
	(*ReplayControlResponse)(nil),    // 13: kprobe.ReplayControlResponse
	(*ReplayStatusRequest)(nil),      // 14: kprobe.ReplayStatusRequest
	(*ReplayStatusResponse)(nil),     // 15: kprobe.ReplayStatusResponse
	(*ReplayEventProto)(nil),         // 16: kprobe.ReplayEventProto
	(*WatchReplayRequest)(nil),       // 17: kprobe.WatchReplayRequest
	(*WatchReplayResponse)(nil),      // 18: kprobe.WatchReplayResponse
}
var file_kprobe_proto_depIdxs = []int32{
	0,  // 0: kprobe.QueryCausalChainResponse.nodes:type_name -> kprobe.KernelEventProto
	1,  // 1: kprobe.QueryCausalChainResponse.edges:type_name -> kprobe.CausalEdgeProto
	0,  // 2: kprobe.QueryEventsResponse.events:type_name -> kprobe.KernelEventProto
	0,  // 3: kprobe.QueryTimeRangeResponse.events:type_name -> kprobe.KernelEventProto
	0,  // 4: kprobe.StreamEventsResponse.event:type_name -> kprobe.KernelEventProto
	16, // 5: kprobe.WatchReplayResponse.event:type_name -> kprobe.ReplayEventProto
	2,  // 6: kprobe.KprobeService.QueryCausalChain:input_type -> kprobe.QueryCausalChainRequest
	4,  // 7: kprobe.KprobeService.QueryEvents:input_type -> kprobe.QueryEventsRequest
	6,  // 8: kprobe.KprobeService.QueryTimeRange:input_type -> kprobe.QueryTimeRangeRequest
	8,  // 9: kprobe.KprobeService.StreamEvents:input_type -> kprobe.StreamEventsRequest
	10, // 10: kprobe.ReplayService.StartReplay:input_type -> kprobe.StartReplayRequest
	12, // 11: kprobe.ReplayService.Control:input_type -> kprobe.ReplayControlRequest
	14, // 12: kprobe.ReplayService.Status:input_type -> kprobe.ReplayStatusRequest
	17, // 13: kprobe.ReplayService.WatchReplay:input_type -> kprobe.WatchReplayRequest
	3,  // 14: kprobe.KprobeService.QueryCausalChain:output_type -> kprobe.QueryCausalChainResponse
	5,  // 15: kprobe.KprobeService.QueryEvents:output_type -> kprobe.QueryEventsResponse
	7,  // 16: kprobe.KprobeService.QueryTimeRange:output_type -> kprobe.QueryTimeRangeResponse
	9,  // 17: kprobe.KprobeService.StreamEvents:output_type -> kprobe.StreamEventsResponse
	11, // 18: kprobe.ReplayService.StartReplay:output_type -> kprobe.StartReplayResponse
	13, // 19: kprobe.ReplayService.Control:output_type -> kprobe.ReplayControlResponse
	15, // 20: kprobe.ReplayService.Status:output_type -> kprobe.ReplayStatusResponse
	18, // 21: kprobe.ReplayService.WatchReplay:output_type -> kprobe.WatchReplayResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kprobe_proto_init() }
func file_kprobe_proto_init() {
	if File_kprobe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kprobe_proto_rawDesc), len(file_kprobe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kprobe_proto_goTypes,
		DependencyIndexes: file_kprobe_proto_depIdxs,
		MessageInfos:      file_kprobe_proto_msgTypes,
	}.Build()
	File_kprobe_proto = out.File
	file_kprobe_proto_goTypes = nil
	file_kprobe_proto_depIdxs = nil
}
