// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/kprobe.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KprobeService_QueryCausalChain_FullMethodName = "/kprobe.KprobeService/QueryCausalChain"
	KprobeService_QueryEvents_FullMethodName      = "/kprobe.KprobeService/QueryEvents"
	KprobeService_QueryTimeRange_FullMethodName   = "/kprobe.KprobeService/QueryTimeRange"
	KprobeService_StreamEvents_FullMethodName     = "/kprobe.KprobeService/StreamEvents"
)

// KprobeServiceClient is the client API for KprobeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KprobeServiceClient interface {
	QueryCausalChain(ctx context.Context, in *QueryCausalChainRequest, opts ...grpc.CallOption) (*QueryCausalChainResponse, error)
	QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error)
	QueryTimeRange(ctx context.Context, in *QueryTimeRangeRequest, opts ...grpc.CallOption) (*QueryTimeRangeResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error)
}

type kprobeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKprobeServiceClient(cc grpc.ClientConnInterface) KprobeServiceClient {
	return &kprobeServiceClient{cc}
}

func (c *kprobeServiceClient) QueryCausalChain(ctx context.Context, in *QueryCausalChainRequest, opts ...grpc.CallOption) (*QueryCausalChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryCausalChainResponse)
	err := c.cc.Invoke(ctx, KprobeService_QueryCausalChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kprobeServiceClient) QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryEventsResponse)
	err := c.cc.Invoke(ctx, KprobeService_QueryEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kprobeServiceClient) QueryTimeRange(ctx context.Context, in *QueryTimeRangeRequest, opts ...grpc.CallOption) (*QueryTimeRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTimeRangeResponse)
	err := c.cc.Invoke(ctx, KprobeService_QueryTimeRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kprobeServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KprobeService_ServiceDesc.Streams[0], KprobeService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, StreamEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KprobeService_StreamEventsClient = grpc.ServerStreamingClient[StreamEventsResponse]

// KprobeServiceServer is the server API for KprobeService service.
// All implementations must embed UnimplementedKprobeServiceServer
// for forward compatibility.
type KprobeServiceServer interface {
	QueryCausalChain(context.Context, *QueryCausalChainRequest) (*QueryCausalChainResponse, error)
	QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error)
	QueryTimeRange(context.Context, *QueryTimeRangeRequest) (*QueryTimeRangeResponse, error)
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error
	mustEmbedUnimplementedKprobeServiceServer()
}

// UnimplementedKprobeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKprobeServiceServer struct{}

func (UnimplementedKprobeServiceServer) QueryCausalChain(context.Context, *QueryCausalChainRequest) (*QueryCausalChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryCausalChain not implemented")
}
func (UnimplementedKprobeServiceServer) QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryEvents not implemented")
}
func (UnimplementedKprobeServiceServer) QueryTimeRange(context.Context, *QueryTimeRangeRequest) (*QueryTimeRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTimeRange not implemented")
}
func (UnimplementedKprobeServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedKprobeServiceServer) mustEmbedUnimplementedKprobeServiceServer() {}
func (UnimplementedKprobeServiceServer) testEmbeddedByValue()                       {}

// UnsafeKprobeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KprobeServiceServer will
// result in compilation errors.
type UnsafeKprobeServiceServer interface {
	mustEmbedUnimplementedKprobeServiceServer()
}

func RegisterKprobeServiceServer(s grpc.ServiceRegistrar, srv KprobeServiceServer) {
	// If the following call panics, it indicates UnimplementedKprobeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KprobeService_ServiceDesc, srv)
}

func _KprobeService_QueryCausalChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCausalChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KprobeServiceServer).QueryCausalChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KprobeService_QueryCausalChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KprobeServiceServer).QueryCausalChain(ctx, req.(*QueryCausalChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KprobeService_QueryEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KprobeServiceServer).QueryEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KprobeService_QueryEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KprobeServiceServer).QueryEvents(ctx, req.(*QueryEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KprobeService_QueryTimeRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KprobeServiceServer).QueryTimeRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KprobeService_QueryTimeRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KprobeServiceServer).QueryTimeRange(ctx, req.(*QueryTimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KprobeService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KprobeServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, StreamEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KprobeService_StreamEventsServer = grpc.ServerStreamingServer[StreamEventsResponse]

// KprobeService_ServiceDesc is the grpc.ServiceDesc for KprobeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KprobeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kprobe.KprobeService",
	HandlerType: (*KprobeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryCausalChain",
			Handler:    _KprobeService_QueryCausalChain_Handler,
		},
		{
			MethodName: "QueryEvents",
			Handler:    _KprobeService_QueryEvents_Handler,
		},
		{
			MethodName: "QueryTimeRange",
			Handler:    _KprobeService_QueryTimeRange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _KprobeService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/kprobe.proto",
}
